version: '3.9'
services:
    el-node:
        image: p202io/el-node:latest
        container_name: el-node
        restart: always
        volumes:
            - ./data/el-node:/data
        networks:
            - node
        ports:
            - "30303:30303"
            - "30303:30303/udp"
            #- "6060:6060"
            - "8545:8545"
            #- "8546:8546"
            - "8551:8551"
        command:
            - --p202-mainnet
            - --config=/data/config.yml
            - --datadir=/data
            - --gcmode=archive
            - --http

    cl-node:
        image: p202io/cl-node:latest
        container_name: cl-node
        restart: always
        volumes:
            - ./data/cl-node:/data
            - ./data/el-node:/el-node
        networks:
            - node
            - validator
        ports:
            - "3500:3500"
            - "4000:4000"
            #- "6060:6060"
            #- "8080:8080"
            - "12000:12000/udp"
            - "13000:13000"
        command:
            - --p202-mainnet
            - --accept-terms-of-use
            - --config-file=/data/config.yml
            - --datadir=/data
            - --execution-endpoint=/el-node/geth.ipc
            - --jwt-secret=/el-node/geth/jwtsecret
        depends_on:
            - el-node

networks:
    node:
    validator:
